language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --ignore=E124,E128 --exclude=tests,migrations cities_light"
  - rm -rf test_project/db.sqlite
  - python test_project/manage.py syncdb
  - python test_project/manage.py migrate
script:
  - python setup.py test
